
#  Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzZDNmM2IyOS02ZWYzLTQwMjEtODExZS1kMGI0YjRmMzM0YzYiLCJpYXQiOjE3MDgzNTMyMjAsImV4cCI6MTcwODQzOTYyMH0.he7WkRRaQWw9bQXZ-gpaG508faXe1QkW1DGSmERHtjQ
////////////////////////////////////////////////////////////////////////////////////////
### POsts 
### create a post
POST http://localhost:8800/api/advance
Content-Type: application/json

{    
  "EmployeeID": 2,
  "Date": "2020-01-10",
  "Amount": 1000.0  
}

### updating a single post
PUT http://localhost:8800/api/advance/1
Content-Type: application/json

{
 "EmployeeID": 1,
  "Date": "2020-01-10",
  "Amount": 1000.0  
}


### Fetching/getting all posts
GET http://localhost:8800/api/advance



### Fetching/getting single post
GET http://localhost:8800/api/advance/1



### Deleting a single post
DELETE  http://localhost:8800/api/advance/1


